FROM apache/airflow:2.1.1-python3.8
COPY ./requirements_airflow.txt .
RUN pip install -r requirements_airflow.txt

USER root
RUN apt-get update &&  apt-get autoremove && apt-get autoclean

# Install OpenJDK-11
RUN apt-get install -y openjdk-11-jdk ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

RUN apt-get install wget -y
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install ./google-chrome-stable_current_amd64.deb -y
